### ISSUE TITLE
I need to speak with MCrafterzz.

### ISSUE THREAD

**Issue by theonerm2** [MarcusElg/BlockoutTools#1]
I just need to talk to you about something. Are you MCrafterzz? I'd like to use the road tool you made in my asset. It's a City generator tool for Unity. I don't have a way to make roads in it yet. I've been requiring Gena Pro to use my asset because it needs something to make the roads. I'd really like to be able to use the Pro version of the road tool because of the terrain modification. But if you wouldn't be ok with that I guess I could still use the free MIT licensed version and try to whip up my own terrain modification or just use it on flat terrain. A response would be much appreciated.

**Comment by MarcusElg** [comment]
It's now available under a MIT license as I no longer plan to update it: https://github.com/MarcusElg/Road-Creator-Pro
